settings:
  listItemIndent: '1'
  rule: '-'
plugins:
  - - remark-lint-blockquote-indentation
    - - error
      - 2

  - - remark-lint-emphasis-marker
    - - error
      - _

  - - remark-lint-file-extension
    - - error
      - md

  - - remark-lint-final-newline
    - - error

  - - remark-lint-first-heading-level
    - - error
      - 1

  - - remark-lint-heading-increment
    - - error

  - - remark-lint-heading-style
    - - error
      - atx

  - - remark-lint-list-item-bullet-indent
    - - error

  - - remark-lint-list-item-content-indent
    - - error

  - - remark-lint-list-item-indent
    - - error
      - space

  - - remark-lint-no-auto-link-without-protocol
    - - error

  - - remark-lint-no-blockquote-without-caret
    - - error

  - - remark-lint-no-consecutive-blank-lines
    - - error

  - - remark-lint-no-emphasis-as-heading
    - - error

  - - remark-lint-no-heading-content-indent
    - - error

  - - remark-lint-no-heading-indent
    - - error

  - - remark-lint-no-heading-like-paragraph
    - - error

  - - remark-lint-no-heading-punctuation
    - - error
      - '.,;:!'

  - - remark-lint-no-inline-padding
    - - error

  - - remark-lint-no-table-indentation
    - - error

  - - remark-lint-ordered-list-marker-style
    - - error
      - '.'

  - - remark-lint-ordered-list-marker-value
    - - error
      - ordered

  - - remark-lint-strong-marker
    - - error
      - '*'

  - - remark-lint-table-cell-padding
    - - error
      - consistent

  - - remark-lint-table-pipe-alignment
    - - error

  - - remark-lint-unordered-list-marker-style
    - - error
      - '-'
