#!/usr/bin/env bash

now="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/node_modules/.bin/now"

# Grab the deploy ID from the running site
existing_id=$($now -t "$NOW_TOKEN" ls aliemcards | tail -n 2 | head -n 1 | awk '{print $1}')

# Deploy changes to a fresh URL
$now -C \
    -t "$NOW_TOKEN" \
    -n aliemcards \
    -e NODE_ENV='production' \
    -e ALIEM_API_KEY="$ALIEM_API_KEY" \
    "$(pwd)"

# Get the deploy ID of the fresh deploy
deployment_id=$($now ls aliemcards | head -n 5 | tail -n 1 | awk '{print $1}')

# Move the URL symbolic link to the new deploy
$now ln -C \
    -t "$NOW_TOKEN" \
    "$deployment_id" aliemcards

# Remove the old version
$now rm -y "$existing_id"
